def menu():
    print(' ')
    print('**DIGITE O CODIGO DE ALGUMA DAS OPÇÕES**')
    print('1- FAZER NOVA BUSCA')
    print('2- ADICIONAR ITEM AO CARRINHO')
    print('3- VISUALIZAR OS ITENS DO CARRINHO')
    print('4- REMOVER PRODUTO DO CARRINHO')
    print('5- CADASTRAR PRODUTO')
    print('6- FINALIZAR VENDA')
    print('7- SAIR DO SISTEMA')
    print(' ')